define(
	{
		"base":"resources/avatars/et004/",
		"bone":"bone.csf",
		"meshSet":[
			{
				"name":"normal",
				"mesh":["mesh1.cmf","mesh2.cmf"]
			}
		],
		"texture":"feidie_01.jpg",
		"animation":{
			"fly":{"alias":"fly","type":1,"name":"ani1.caf"},
			"faint":{"alias":"faint","type":1,"name":"ani2.caf"},
			"dead":{"alias":"dead","type":1,"name":"ani3.caf"}
        }
	}
);