define(function(C,p){function D(a){for(var c in h){var d=h[c];if(!(a!=d.FOR||d.CHECKED)){d.NODE=SFNode.get(d.NAME);if(!d.NODE){k.warn("加载 ResourceLoader 警告 : 未找到加载"+d.FOR+"所需要使用的Group组节点"+d.NAME+",该组节点将被动态创建");var f=new SFNode("DEF "+d.NAME+" "+d.TYPE+"{}");f.children[0]&&(f=f.children[0]);d.NODE=f;SFNode.get("lyinux->userscenegraphroot").children[0].addChild(d.NODE)}d.CHECKED=!0}}}function r(a){var c=a.uri;"scene"==a.type?c=v+c:"ui"==a.type?c=w+c:"item"==a.type?c=x+c:k.warn("未支持的资源type:"+a.type);
c=fullpath(c);return c=c.replace(/\/|\.|:/g,"_")}function y(a,c){a.children?a.children.forEach(function(a){y(a,c)}):a.choice&&a.choice.forEach(function(a){y(a,c)});"Inline"==a.getType()&&(a.success=!1,c.push(a))}var s=this,k=C("core/Logger").getLog(),j=C("core/Event").getInstance("ResLoad"),G={ui:!0,scene:!0,item:!0},h={UIRES:{NAME:"__rs_UIG",TYPE:"Group",FOR:"ui",NODE:{},CHECKED:!1},UINODE:{NAME:"__uiG",TYPE:"GUIGroup",FOR:"ui",NODE:{},CHECKED:!1},SCENE:{NAME:"__sceneG",TYPE:"Group",FOR:"scene",
NODE:{},CHECKED:!1},ITEM:{NAME:"__itemG",TYPE:"Switch",FOR:"item",NODE:{},CHECKED:!1}},z=SFNode.get("__camera"),H=new SFVec3f(0,0,-100),w="inline/ui/",u="resources/ui/",v="resources/scenes/",x="resources/models/",E={},n={},F={},A={},B={};/eventIn\sSFBool\sload_success_in/.test(s+"")?s.load_success_in=function(){var a=getEmitter().getName();E[a]=!0;j.trigger(a)}:k.warn("加载 ResourceLoader 错误 : Script脚本中,未找到 eventIn SFBool load_success_in 的定义,模块将不能正常工作!");z||k.warn("未找到名称为__camera的摄像机节点,加载场景可能会出现意外情况,建议将摄像机节点命名为 __camera！");
p.config=function(a){a&&(a.res_scene&&(v=a.res_scene),a.res_item&&(x=a.res_item),a.res_ui&&(u=a.res_ui),a.node_ui&&(w=a.node_ui))};p.load=function(a,c){var d=Date.now(),f={},q={},m=[],t=0;a.forEach(function(a){if("ui"==a.type){D("ui");if(!a.depends){k.warn("UI未指定依赖资源:"+a.uri+","+d);return}a.depends.forEach(function(a){q[a.set]=a})}else D(a.type);a=r(a);m[t]=a;t++;f[a]&&k.warn("重复加载,可能会造成混乱:"+a+","+d);f[a]=!0});var l=function(a,b){if(f[a]||b){var d;a:{for(d in f)if(!E[d]){d=!1;break a}d=!0}d&&(j.unbind("all",
l),c&&c(m),c=null)}};j.bind("all",l);var g,e=[],b;for(g in q)F[g]||(e.push(q[g]),F[g]=!0);0<e.length&&(b="GUIGroup { imagesets [\n",e.forEach(function(a){0!==(a.code&1)&&(b+=' "'+u+a.set+'/UI.imageset" \n')}),b+=" ] lookfeels [ \n",e.forEach(function(a){0!==(a.code&2)&&(b+=' "'+u+a.set+'/UI.looknfeel" \n')}),b+=" ] schemes [ \n",e.forEach(function(a){0!==(a.code&4)&&(b+=' "'+u+a.set+'/UI.scheme" \n')}),b+=" ]}",g=(new SFNode(b)).children[0],h.UIRES.NODE.addChild(g));a.forEach(function(a){var b=r(a);
if(n[b])"scene"==a.type&&(SFNode.get(b+"Swi").whichChoice=-3);else if(G[a.type])if("ui"==a.type){var c,e;c="DEF "+b+' Inline{ url "'+w+a.uri+'"}\n';c+="ROUTE "+b+".success TO "+s.getName()+".load_success_in";try{var g=function(){j.unbind(b,g);a.isChild&&h.UINODE.NODE.removeChild(n[b])};j.bind(b,g);e=(new SFNode(c)).getChild(0);h.UINODE.NODE.addChild(e);n[b]=e}catch(l){k.error(l.stack)}}else if("scene"==a.type){var f;c=z.position.add(z.orientation.multVec(H));e="Transform{ \n  children[ \n"+("    DEF "+
b+"Swi Switch{choice[ \n");e+="        DEF "+b+' Inline{ url "'+v+a.uri+'"} ';e+="    ]whichChoice -3}]";e+="  scale 0.001 0.001 0.001 \n";e+="  translation "+c.toString()+" \n";e+="}\n";try{(f=new SFNode(e))&&SFNode.createRoute(f.children[0].choice[0],"success",s,"load_success_in");var t=function(){j.unbind(b,t);f.scale.setValue(1,1,1);f.translation.setValue(0,0,0)};j.bind(b,t);h.SCENE.NODE.addChild(f);n[b]=f}catch(m){k.error("在loadScene中出现错误:"+m.stack)}}else{if("item"==a.type){e="DEF "+b+' Inline{ url "'+
x+a.uri+'"} ';try{(c=new SFNode(e))&&SFNode.createRoute(c.children[0],"success",s,"load_success_in");var q=function(){j.unbind(b,q)};j.bind(b,q);h.ITEM.NODE.addChild(c);n[b]=c}catch(p){k.error("在loadScene中出现错误:"+p.stack)}}}else k.warn("未支持的资源type:"+a.type+","+d)});l("",!0)};p.render=function(a,c,d){function f(d){var l;a:{l=a.loadList;var g,e,b,h,j,m;b=l.length;for(g=0;g<b;g++)if(j=A[r(l[g])]){h=j.length;for(e=0;e<h;e++)if(m=j[e],!m.success){l=!1;break a}}l=!0}l?"function"!=typeof c?k.warn("render方法未指定回调"):
c(d):setTimeout(f,0.5)}if(d&&h&&h.SCENE&&h.SCENE.NODE&&h.SCENE.NODE.children){d=h.SCENE.NODE.children;for(var j=d.length,m=0;m<j;m++)d[m].children[0].whichChoice=-1}this.load(a.loadList,function(){var c={},d=[];a.loadList.forEach(function(a){var b=r(a);"scene"==a.type&&(d.push(b),n[b].whichChoice=0,c[b]=!0,B[b]=!0);if(a.root&&!A[b]){a=SFNode.get(a.root);var f=[];a?(y(a,f),A[b]=f):k.warn("无法获取根节点:"+b)}});for(var g in B)c[g]||(n[g].whichChoice=-1,delete B[g]);f(d)})};p.getScene=function(a){a=r({type:"scene",
uri:a})+"Swi";return h.SCENE.NODE.getChild(a)}});
