define(function(w,s,q){var r=this,c=r.vQuery=r.$=function(){},u=Object.prototype.toString,v=Object.prototype.hasOwnProperty,x="action selectfile recieve method state response submit preLoad result snapshot saveAsFile title filename".split(" "),d;"undefined"!==typeof s?("undefined"!==typeof q&&q.exports&&(s=q.exports=c),d=w("../core/Logger").getLog(),s.vQuery=c):d.off=d.error=d.warn=d.info=d.debug=print;c.extend=function(){var b=arguments[0]||{},d=1,g=arguments.length,e=!1,l,h,m,j;"boolean"===typeof b&&
(e=b,b=arguments[1]||{},d=2);"object"!==typeof b&&!c.isFunction(b)&&(b={});g===d&&(b=this,--d);for(;d<g;d++)if(null!=(l=arguments[d]))for(h in l)m=b[h],j=l[h],b!==j&&(e&&j&&(c.isPlainObject(j)||c.isArray(j))?(m=m&&(c.isPlainObject(m)||c.isArray(m))?m:c.isArray(j)?[]:{},b[h]=c.extend(e,m,j)):void 0!==j&&(b[h]=j));return b};c.extend({isFunction:function(b){return"[object Function]"===u.call(b)},isArray:function(b){return"[object Array]"===u.call(b)},isPlainObject:function(b){if(!b||"[object Object]"!==
u.call(b)||b.constructor&&!v.call(b,"constructor")&&!v.call(b.constructor.prototype,"isPrototypeOf"))return!1;for(var c in b);return void 0===c||v.call(b,c)},each:function(b,c,d){var e,l=0,h=b.length;if(d)if(void 0===h)for(e in b){if(!1===c.apply(b[e],d))break}else for(;l<h&&!1!==c.apply(b[l++],d););else if(void 0===h)for(e in b){if(!1===c.call(b[e],e,b[e]))break}else for(d=b[0];l<h&&!1!==c.call(d,l,d);d=b[++l]);return b}});c.extend({param:function(b){function d(b,c){g[g.length]=encodeURIComponent(b)+
"="+encodeURIComponent(c)}var g=[];if(c.isArray(b))c.each(b,function(){d(this.name,this.value)});else for(var e in b)c.isArray(b[e])?c.each(b[e],function(){d(e,this)}):d(e,c.isFunction(b[e])?b[e]():b[e]);return g.join("&")}});c.extend(function(){function b(a,k,b){var f;d.info("CCJS-Ajax：Form method---"+k);d.info("CCJS-Ajax：Form data---"+JSON.stringify(b));if("GET"==k)f=(new SFNode("Form {recieve TRUE method GET }")).getChild(0);else if("POST"==k){f="Form {recieve TRUE method POST \n";var e="";c.isPlainObject(b)?
(c.each(b,function(a,b){if(-1!=x.indexOf(a))return d.error("CCJS-Ajax：data数据字段"+a+"不能与lyinux表单自身字段相同！"),e="",!1;e+="SFString "+a+' "'+b+'" \n'}),b=e):(d.error("CCJS-Ajax：data的格式不正确，只能是Object"),b="");f=f+b+"}";d.info("CCJS-Ajax：新建POST方式Form---"+f);f=(new SFNode(f)).getChild(0)}else d.error("CCJS-Ajax：type的值设置不正确，只能是GET或POST"),f=void 0;this.node=f;this.groupNode=a;this.method=k;a.addChild(this.node)}function s(a){switch(a){case -1:break;case 0:a=0;for(var b=g.length;a<b;a++)if(0==g[a].getState()){if("POST"==
g[a].method){var c=g.splice(a,1)[0].callback().complete().disconnect(),f=c.groupNode;f.removeChild(c.node);delete c.node;d.info("CCJS-Ajax：POST方式Form从服务器获取数据成功，将Form从FormGroup中删除")}else e.push(g.splice(a,1)[0].callback().complete().disconnect()),d.info("CCJS-Ajax：GET方式Form从服务器获取数据成功");a--;b--}break;default:a=0;for(b=g.length;a<b;a++)h=g[a].getState(),0<g[a].getState()&&("POST"==g[a].method?(c=g.splice(a,1)[0].error(h).complete().disconnect(),f=c.groupNode,f.removeChild(c.node),delete c.node,d.error("CCJS-Ajax：POST方式Form从服务器获取数据失败，将Form从FormGroup中删除")):
(e.push(g.splice(a,1)[0].error(h).complete().disconnect()),d.error("CCJS-Ajax：GET方式Form从服务器获取数据失败")),a--,b--)}}var g=[],e=[],l=(1E4*Date.now()).toFixed(0),h=-1,m=/^(?:vrml|cc6|lyx)$/i,j=null;Browser.getVersion();var q=0,t={};c.excute_tdd=function(a){var b=t[a].s,c=t[a].unit;print("TEST--\x3e"+c.name+"--\x3e"+c.ret);if(b.success){var d=b.success;switch(b.dataType){case "jsonp":case "json":d.call(null,(new Function("return "+c.ret))());break;case "vrml":case "cc6":case "lyx":d.call(null,new SFNode(c.ret));
break;default:d.call(null,c.ret)}}b.complete&&b.complete();delete t[a]};b.prototype={setAction:function(a){this.node.setField("action",a);return this},setState:function(){this.node.setField("state",-1);return this},getState:function(){return this.node.state},submit:function(){m.test(this.dt)?this.node.setField("preLoad",!0):this.node.setField("preLoad",!1);this.node.setField("submit",!0);return this},setCallBack:function(a){this.callback=function(){var b=this.node.response;if(this.jsonp)(new Function(b))();
else if("json"==this.dt)a.call(null,(new Function("return "+b))());else if(m.test(this.dt))a.call(null,this.node.result);else if("xml"==this.dt)try{a.call(null,new XML(b.replace(/<\?[^>]+\?>\s*/,"")))}catch(c){print(c+"\n dateType=XML时执行回调函数发生错误，请确认返回的数据是否是xml字符串？\n"+b.replace(/<\?[^>]+\?>\s*/,""))}else a.call(null,b);return this};return this},setComplete:function(a){this.complete=function(){(a||function(){})();return this};return this},setError:function(a){this.error=function(b){print("ERROR state:"+
b+"\nIN ACTION:"+this.node.action+"\nRESPONSE:"+this.node.response);(a||function(){})(b);return this};return this},connect:function(a,b){this._script=a;this._listener=b;SFNode.createRoute(this.node,"state",a,b);return this},disconnect:function(){SFNode.removeRoute(this.node,"state",this._script,this._listener);this.setAction("");this.node.setField("response","");return this},setJsonp:function(a){this.jsonp=a;return this},setDataType:function(a){this.dt=a||"text";return this}};return{ajax:function(a){a=
c.extend(!0,{},this.ajaxSettings,a);var k,p=/=\?(&|$)/g,f,n=a.type.toUpperCase(),h=a.data;a.data&&(a.processData&&"string"!==typeof a.data)&&(a.data=c.param(a.data));if("jsonp"==a.dataType){if("GET"==n)a.url.match(p)||(a.url+=(a.url.match(/\?/)?"&":"?")+(a.jsonp||"callback")+"=?");else if(!a.data||!a.data.match(p))a.data=(a.data?a.data+"&":"")+(a.jsonp||"callback")+"=?";a.dataType="json"}if("json"==a.dataType&&(a.data&&a.data.match(p)||a.url.match(p)))k="jsonp"+l++,a.data&&(a.data=(a.data+"").replace(p,
"="+k+"$1")),a.url=a.url.replace(p,"="+k+"$1"),r[k]=function(b){f=b;a.success(f,void 0);r[k]=void 0;try{delete r[k]}catch(c){}};a.data&&"GET"==n?(a.url+=(a.url.match(/\?/)?"&":"?")+a.data,a.data=null):a.data&&"POST"==n&&(a.data=h,d.info("CCJS-Ajax：POST方式下，使用原始数据---"+a.data+"---而不是追加到url后"));if(a.beforeSend&&!1===a.beforeSend(a))return!1;if(!a.testUnit)return p=a,n=c.extend(!0,{},{name:"TDD",delay:0.5,ret:"{test:1}"},p.testUnit),t[++q+""]={s:p,unit:n},setTimeout("vQuery.excute_tdd("+q+")",n.delay,
1),this;0==e.length||"POST"==n?(j=new b(a.group_node||SFNode.get("lyinux->userscenegraphroot").getChild(0),n,a.data),d.info("CCJS-Ajax："+n+"方式下，新建一个FORM表单")):(j=e.pop(),d.info("CCJS-Ajax："+n+"方式下，从sleep_pool取一个FORM表单"));g.push(j);d.info("CCJS-Ajax："+a.url);j.setAction(a.url).setCallBack(a.success).setComplete(a.complete).setError(a.error).setState(-1).setJsonp(k).setDataType(a.dataType).connect(a.thisScript,a.stateListener).submit();0<a.timeout&&setTimeout("print('timeout 超时)",+a.timeout);return j},
get:function(a,b,d,f,e){c.isFunction(b)&&(f=f||d,d=b,b=null);"string"!==typeof f&&(e=e||f,f="text");return c.ajax({type:"GET",url:a,data:b,success:d,dataType:f,testUnit:e})},post:function(a,b,d,f,e){c.isFunction(b)&&(f=f||d,d=b,b={});"string"!==typeof f&&(e=e||f,f="text");return c.ajax({type:"POST",url:a,data:b,success:d,dataType:f,testUnit:e})},getJSON:function(a,b,d,e){c.isFunction(b)&&(e=e||d,d=b,b=null);return c.get(a,b,d,"json",e)},ajaxSettings:{url:"",global:!0,type:"POST",processData:!0},ajaxSetup:function(a){a=
c.extend(c.ajaxSettings,a);a.stateListener&&"string"==typeof a.stateListener&&(r[a.stateListener]=s)}}}())});
