define(function(require,exports,module){var root=this,state=false,log=require("core/Logger").getLog();var Pool=require("node/NodeCachePool");var fruitResPath="/resources/models/fruits/",tranUFOResPath="/resources/models/tranUFO/";var Config=require("./Config"),Timer=require("core/Timer"),TimerEvent=require("core/Event").getInstance("Timer"),GameEvent=require("core/Event").getInstance("GameEvent"),ActionEvent=require("core/Event").getInstance("ActionEvent");var group;var ufoFruitGap=-1.2;var fruitArray=
[];var ammoArray=[];var gpause=false;var activateFruit=null;var previousFruit=null;var selectFruitName="pingguo";var screenFruitNum;var aspectRatio=16/9;var heightAngle=0.3;var cameraPos=new SFVec3f(0,0,0);var visualFar=70;var visualNear=50;var ammoStartSpeed=10;var ammoEndSpeed=100;var ammoSpeed=5;var ammoAccSpeed=25;var fruitBackSpeed=25;var fruitAppealSpeed=25;var tranUFOEscapeSpeed=16;var tranUFOAndFruitStartSpeed=0.3;var tranUFOAndFruitEndSpeed=0.2;var hitERange=1.2;var fruitERange=0.5;var escapeERange=
0.5;var moveERange=0.2;var partAreaMode="config";var areaNum=partAreaMode=="config"?Config.area.areaNum:3;var kl=2.8;var kr=2;var leftKeepAngle=0;var verticalAngleRange=10;var fruitGenMode="Down2Top";var fruitGenMinYPercent=0.3;var fruitGenMaxYPercent=0.8;var fruitOut4TopPercent=0.7;var fruitOut4LeftYMinPercent=0.1;var fruitOut4LeftYMaxPercent=0.7;var fruitOutLeftXRadio=0.8;var fruitLeftOdds=0.7;var fruitOut4RightYMinPercent=0.1;var fruitOut4RightYMaxPercent=0.7;var fruitOutRightXRadio=0.8;var fruitRightOdds=
0.7;var visualFace=50;var isStartObtain=false;var debug=Config.mode=="debug"?true:false;var testRightHand=new SFVec3f(0,0,-10);var SystemEvent=require("events/SystemEvent");var Keycode=require("utils/Keycode");var targetNode;function test(){SystemEvent.bind("keyUp",function(v){if(v==Keycode.NUM1)getFruitAmmo(calRadian(66),testRightHand,true);else if(v==Keycode.NUM2)getFruitAmmo(calRadian(82),testRightHand,true);else if(v==Keycode.NUM3)getFruitAmmo(calRadian(90),testRightHand,true);else if(v==Keycode.NUM4)getFruitAmmo(calRadian(98),
testRightHand,true);else if(v==Keycode.NUM5)getFruitAmmo(calRadian(135),testRightHand,true);else if(v==Keycode.NUM6)getFruitAmmo(calRadian(90),testRightHand,false);else if(v==Keycode.NUM0)hurlFruitAmmo(selectFruitName,testRightHand,targetNode);else if(v==Keycode.S){var holdTarget=Config.fruits[Math.floor(Math.random()*Config.fruits.length)].name;log.info();exports.createFruit(holdTarget)}else if(v==Keycode.P)exports.pause(!gpause);else if(v==Keycode.R){exports.destroy();exports.init()}})}exports.init=
function(){if(!state){state=true;initView();if(debug)exports.createFruit("pingguo");enabledEvents(true);if(debug){test();showUFO()}}};function initView(){var groupStr="DEF futitTrans Transform {translation 0 0 0 children [Group {children [TransparencyType{value DELAYED_BLEND}]}]}";group=new SFNode(groupStr);GROUPMID.addChild(group)}exports.pause=function(isPause){gpause=isPause};exports.createFruit=function(fruitName){var obj;if(fruitArray.length>0){for(var i=0;i<fruitArray.length;i++){obj=fruitArray[i];
unbindTimer(obj.runFunc);unbindTimer(obj.fightFunc);unbindTimer(obj.giveUpFunc);unbindTimer(obj.escapeFunc);group.children[0].removeChild(obj.groupNode);Pool.remove(obj.fruitAmmo.id);Pool.remove(obj.transportUFO.id)}fruitArray=[]}if(ammoArray.length>0){for(var i=0;i<ammoArray.length;i++){obj=ammoArray[i];unbindTimer(obj.func);group.children[0].removeChild(obj.node.node);Pool.remove(obj.node.id)}ammoArray=[]}selectFruitName=fruitName;fruitFactory(fruitName);activateFruit=null;previousFruit=null;for(var i=
0;i<fruitArray.length;i++){obj=fruitArray[i];group.children[0].addChild(obj.groupNode);transportFruit(obj)}};function unbindTimer(func){if(func)TimerEvent.unbind("time",func)}function transportFruit(obj){if(!gpause){var init=true;TimerEvent.bind("time",function(t,dt){if(init){obj.runFunc=arguments.callee;init=false}var condition=obj.status=="create"||obj.status=="giveUp";if(!obj.stop&&condition&&!gpause){var isEnd=moveTranUFOAndFruit(obj,dt);if(isEnd){clear(obj);unbindTimer(obj.runFunc);screenFruitNum--;
log.debug("screenFruitNum:"+screenFruitNum);if(screenFruitNum==0)GameEvent.trigger("stateEvent","fruitDisappear")}}})}}function clear(obj){obj.status="destroy";group.children[0].removeChild(obj.groupNode);remove(fruitArray,obj);Pool.remove(obj.fruitAmmo.id);Pool.remove(obj.transportUFO.id)}function remove(array,obj){for(var i=0;i<array.length;i++)if(array[i]==obj)array.splice(i,1)}function moveTranUFOAndFruit(obj,dt){var v=obj.speed;obj.transportUFO.node.translation=plus(obj.transportUFO.node.translation,
v.multiply(dt));obj.fruitAmmo.node.translation=plus(obj.fruitAmmo.node.translation,v.multiply(dt));var distance=getVector(obj.transportUFO.node.translation,obj.ufoEndTran).length();if(distance<=moveERange)return true;else{setSpeedVector(obj,1-distance/obj.totalDistance);return false}}function fruitFactory(fruitName){var obj=null;var fruitAreaIndex=Math.floor(getRandomNum(0,areaNum));for(var i=0;i<areaNum;i++){if(i==fruitAreaIndex)obj=getTranUFOAndFruit(fruitName,i,1);else obj=getTranUFOAndFruit(fruitName,
i,0);fruitArray.push(obj)}screenFruitNum=areaNum;log.debug("创建后,screenFruitNum:"+screenFruitNum)}function getTranUFOAndFruit(fruitName,areaIndex,precise){var ufoStartTran,fruitStartTran,ufoEndTran,fruitEndTran;if(fruitGenMode=="Far2Near"){ufoStartTran=getTranUFOPoint(visualFar,areaIndex,-0.5);fruitStartTran=getFruitByTranUFO(ufoStartTran);ufoEndTran=getTranUFOPoint(visualNear,areaIndex,0.5);fruitEndTran=getFruitByTranUFO(ufoEndTran)}else if(fruitGenMode=="Down2Top"){ufoStartTran=getTranUFOPoint2(visualFace,
areaIndex,"start");fruitStartTran=getFruitByTranUFO(ufoStartTran);ufoEndTran=getTranUFOPoint2(visualFace,areaIndex,"end");fruitEndTran=getFruitByTranUFO(ufoEndTran)}var tranUFONode=getTranUFONode();tranUFONode.node.translation.setValue(ufoStartTran);var fruitNodeObj=getFruitNode(fruitName,precise);var fruitNode=fruitNodeObj.node;fruitNode.node.translation.setValue(fruitStartTran);var groupNodeStr="Switch{choice [] whichChoice -3}";var groupNode=(new SFNode(groupNodeStr)).children[0];groupNode.choice[0]=
tranUFONode.node;groupNode.choice[1]=fruitNode.node;var obj={"areaIndex":areaIndex,"fruitName":fruitNodeObj.name,"status":"create","stop":false,"transportUFO":{"node":tranUFONode.node,"id":tranUFONode.id},"fruitAmmo":{"node":fruitNode.node,"id":fruitNode.id},"groupNode":groupNode,"ufoStartTran":ufoStartTran,"fruitStartTran":fruitStartTran,"ufoEndTran":ufoEndTran,"fruitEndTran":fruitEndTran,"runFunc":null,"fightFunc":null,"giveUpFunc":null,"escapeFunc":null,"totalDistance":getVector(ufoStartTran,ufoEndTran).length(),
"fruitSpeed":new SFVec3f(0,0,0),"escapeSpeed":new SFVec3f(0,0,0),"startSpeed":tranUFOAndFruitStartSpeed,"endSpeed":tranUFOAndFruitEndSpeed,"speed":new SFVec3f(0,0,0)};setSpeedVector(obj,0);return obj}function getFruitByTranUFO(tranUFOPos){return new SFVec3f(tranUFOPos.x,tranUFOPos.y-ufoFruitGap,tranUFOPos.z)}function setSpeedVector(obj,percent){var speed=obj.startSpeed-percent*(obj.startSpeed-obj.endSpeed);obj.speed=getSpeedVector(obj.transportUFO.node.translation,obj.ufoEndTran,speed);return obj.speed}
function getVector(p1,p2){return new SFVec3f(p2.x-p1.x,p2.y-p1.y,p2.z-p1.z)}function plus(p1,p2){return new SFVec3f(p2.x+p1.x,p2.y+p1.y,p2.z+p1.z)}function getFruitNode(fruitName,precise){var assignFruit=getFruitByFileName(fruitName);var fruitObj=null;var fruitNum=Config.fruits.length;if(precise>=1)fruitObj=assignFruit;else if(precise<=0){do fruitObj=getFruitById(Math.floor(getRandomNum(0,fruitNum)));while(fruitObj.id==assignFruit.id)}else fruitObj=getFruitById(Math.floor(getRandomNum(0,fruitNum)));
var template="Transform {children[s%]}";var fruitNode=Pool.create(fruitObj.file,template,fruitResPath);return{"node":fruitNode,"name":fruitObj.name,"id":fruitObj.id}}function getTranUFONode(){var tranUFO=Config.tranUFO;var template="Transform { scale 0.5 0.5 0.5 children[s%]}";var tranUFONode=Pool.create(tranUFO.file,template,tranUFOResPath);return tranUFONode}function getFruitByFileName(fruitName){var fruits=Config.fruits;var fruit=null;for(var i=0;i<fruits.length;i++){fruit=fruits[i];if(fruit.name==
fruitName)return fruit}return null}function getFruitById(id){var fruits=Config.fruits;var fruit=null;for(var i=0;i<fruits.length;i++){fruit=fruits[i];if(fruit.id==id)return fruit}return null}function getRandomNum(num1,num2){var min=Math.min(num1,num2);var max=Math.max(num1,num2);return Math.random()*(max-min)+min}function getVisualArea(point,distance){var halfH=distance*Math.tan(heightAngle/2);var halfW=halfH*aspectRatio;var centerAreaPoint=new SFVec3f(point.x,point.y,point.z-distance);var leftBottomPoint=
new SFVec3f(centerAreaPoint.x-halfW,centerAreaPoint.y-halfH,centerAreaPoint.z);var rightTopPoint=new SFVec3f(centerAreaPoint.x+halfW,centerAreaPoint.y+halfH,centerAreaPoint.z);return{"leftBottom":leftBottomPoint,"rightTop":rightTopPoint}}function getTranUFOPoint2(distance,areaIndex,location){var face=getVisualArea(cameraPos,distance);var t=(face.rightTop.x-face.leftBottom.x)/areaNum;var x,y;if(location=="start"){x=getRandomNum(face.leftBottom.x+areaIndex*t,face.leftBottom.x+(areaIndex+1)*t);if(areaIndex==
0)y=0.2*(face.rightTop.y-face.leftBottom.y)+face.leftBottom.y;else y=face.leftBottom.y}else if(location=="end"){x=getRandomNum(face.leftBottom.x+areaIndex*t,face.leftBottom.x+(areaIndex+1)*t);y=face.rightTop.y}return new SFVec3f(x,y,cameraPos.z-distance)}function getTranUFOPoint(distance,areaIndex,range){var randDistance=getRandomNum(distance,distance+range);var face=getVisualArea(cameraPos,randDistance);var t=(face.rightTop.x-face.leftBottom.x)/areaNum;var x,y;if(range<=0){x=getRandomNum(face.leftBottom.x+
areaIndex*t,face.leftBottom.x+(areaIndex+1)*t);var minY=fruitGenMinYPercent*(face.rightTop.y-face.leftBottom.y)+face.leftBottom.y;var maxY=fruitGenMaxYPercent*(face.rightTop.y-face.leftBottom.y)+face.leftBottom.y;y=getRandomNum(minY,maxY)}else if(areaIndex==0)if(Math.random()>=fruitLeftOdds){x=getRandomNum(face.leftBottom.x+areaIndex*t,face.leftBottom.x+(areaIndex+1)*t);y=fruitOut4TopPercent*(face.rightTop.y-face.leftBottom.y)+face.leftBottom.y}else{x=face.leftBottom.x*fruitOutLeftXRadio;var minY=
fruitOut4LeftYMinPercent*(face.rightTop.y-face.leftBottom.y)+face.leftBottom.y;var maxY=fruitOut4LeftYMaxPercent*(face.rightTop.y-face.leftBottom.y)+face.leftBottom.y;y=getRandomNum(minY,maxY)}else if(areaIndex==areaNum-1)if(Math.random()>=fruitRightOdds){x=getRandomNum(face.leftBottom.x+areaIndex*t,face.leftBottom.x+(areaIndex+1)*t);y=fruitOut4TopPercent*(face.rightTop.y-face.leftBottom.y)+face.leftBottom.y}else{x=face.rightTop.x*fruitOutRightXRadio;var minY=fruitOut4RightYMinPercent*(face.rightTop.y-
face.leftBottom.y)+face.leftBottom.y;var maxY=fruitOut4RightYMaxPercent*(face.rightTop.y-face.leftBottom.y)+face.leftBottom.y;y=getRandomNum(minY,maxY)}else{x=getRandomNum(face.leftBottom.x+areaIndex*t,face.leftBottom.x+(areaIndex+1)*t);y=face.rightTop.y}return new SFVec3f(x,y,cameraPos.z-randDistance)}function getInterpolationPoint(startPos,endPos,percent){if(percent>=1)return endPos;if(percent<=0)return startPos;var c=percent/(1-percent);var x=(startPos.x+c*endPos.x)/(1+c);var y=(startPos.y+c*endPos.y)/
(1+c);var z=(startPos.z+c*endPos.z)/(1+c);return new SFVec3f(x,y,z)}function enabledEvents(b){if(b)ActionEvent.bind("holdResult",getFruitAmmo);else ActionEvent.unbind("holdResult",getFruitAmmo)}function getFruitAmmo(angle,rightHand,isActive){needFruitAmmo(true);if(isActive){var obj=isFindFruitAmmo(angle);if(obj!=null&&(obj.status=="create"||obj.status=="giveUp")){startResizeFruitAmmo(obj);previousFruit=activateFruit;activateFruit=obj}else if(obj!=null&&obj.status=="fight")fightForFruitAmmo(obj,rightHand,
selectFruitName);else if(obj==null&&activateFruit!=null&&(activateFruit.status=="fighting"||activateFruit.status=="fight")){giveUpFruitAmmo(activateFruit);previousFruit=activateFruit;activateFruit=null}}else if(activateFruit!=null){giveUpFruitAmmo(activateFruit);previousFruit=activateFruit;activateFruit=null}return obj}function needFruitAmmo(need){isStartObtain=true}function isFindFruitAmmo(angle){if(isStartObtain){var areaIndex,range;for(var i=0;i<fruitArray.length;i++){areaIndex=fruitArray[i].areaIndex;
range=getAngleRange(areaIndex);if(angle>=calRadian(range.minAngle)&&angle<=calRadian(range.maxAngle))return fruitArray[i]}}return null}function getAngleRange(areaIndex){if(partAreaMode=="config"){var obj=Config.area.areas[areaIndex];return obj}else if(partAreaMode=="calculate"){if(areaIndex%2==0)return null;var angleRange;if(areaIndex<(areaNum-1)/2){angleRange=calAngle1(areaIndex,kl,areaNum);if(calGapValid(kl,areaNum,verticalAngleRange,leftKeepAngle)<=1/5);return{"minAngle":angleRange.angle-angleRange.range/
2,"maxAngle":angleRange.angle+angleRange.range/2}}else if(areaIndex==(areaNum-1)/2)return{"minAngle":90-verticalAngleRange/2,"maxAngle":90+verticalAngleRange/2};else{var rNum=(areaNum+1)/2;var t=90/rNum;var index=areaIndex-rNum+1;var centerAngle=90+index*t;return{"minAngle":centerAngle-kr*verticalAngleRange,"maxAngle":centerAngle+kr*verticalAngleRange}}}}function calRadio1(k,n){if(n%2!=1||n<0)return 0;var expNum=(n-1)/2;var sum=0;for(var i=0;i<=expNum;i++)sum+=Math.pow(k,i);return 1/sum}function calAngle1(areaIndex,
k,n){if(areaIndex>=(areaNum-1)/2)return null;var expNum=(n-1)/2;var sumAngle=0;for(var i=0;i<=areaIndex;i++)sumAngle=sumAngle+Math.pow(k,expNum-i)*calRadio1(k,n)*(90-leftKeepAngle);return{"angle":sumAngle+leftKeepAngle,"range":Math.pow(k,expNum-areaIndex)*verticalAngleRange}}function calGapValid(k,n,verticalAngle,leftAngle){var B=90-leftAngle;var c=calRadio1(k,n);var gapAngle=B*c-(1+k)*verticalAngle/2;return gapAngle/verticalAngle}function calRadian(angle){return angle*Math.PI/180}function calAngle(radian){return 180*
radian/Math.PI}function startResizeFruitAmmo(obj){if(isStartObtain&&!gpause){obj.status="fight";obj.stop=true;if(previousFruit)unbindTimer(previousFruit.giveUpFunc);if(activateFruit){activateFruit.status="giveUp";giveUpFruitAmmo(activateFruit)}}}function fightForFruitAmmo(obj,rightHand,fruitName){if(isStartObtain&&!gpause){obj.status="fighting";var startPos=obj.fruitAmmo.node.translation;var endPos=rightHand;var _init=true;obj.fruitSpeed=getSpeedVector(startPos,endPos,fruitAppealSpeed);TimerEvent.bind("time",
function(t,dt){if(_init){obj.fightFunc=arguments.callee;_init=false}var condition=obj.status=="fighting";if(!gpause&&condition){var distance=moveFruit(obj,endPos,dt);if(distance<=fruitERange){unbindTimer(obj.fightFunc);obtainFruitAmmo(obj,fruitName)}}else if(!condition)unbindTimer(obj.fightFunc)})}}function moveFruit(obj,endPos,dt){var v=obj.fruitSpeed;obj.fruitAmmo.node.translation=plus(obj.fruitAmmo.node.translation,v.multiply(dt));var distance=getVector(obj.fruitAmmo.node.translation,endPos).length();
return distance}function getSpeedVector(startPos,endPos,speed){var vector=getVector(startPos,endPos);var nVector=vector.normalize();return nVector.multiply(speed)}function obtainFruitAmmo(obj,fruitName){obj.groupNode.whichChoice=0;if(obj.fruitName==fruitName){obj.status="obtain";log.info("成功获取水果："+fruitName);for(var i=0;i<fruitArray.length;i++)if(fruitArray[i]!=obj){unbindTimer(fruitArray[i].giveUpFunc);giveUpFruitAmmo(fruitArray[i])}needFruitAmmo(false)}else obj.status="abandon";unbindTimer(obj.runFunc);
tranUFOEscape(obj);GameEvent.trigger("getFruit",obj.fruitName)}function tranUFOEscape(obj){if(!gpause){var startPos=obj.transportUFO.node.translation;var endPos=obj.ufoStartTran;var _init=true;obj.escapeSpeed=getSpeedVector(startPos,endPos,tranUFOEscapeSpeed);TimerEvent.bind("time",function(t,dt){if(_init){obj.escapeFunc=arguments.callee;_init=false}if(!gpause){var distance=escape(obj,endPos,dt);if(distance<=escapeERange){unbindTimer(obj.escapeFunc);group.children[0].removeChild(obj.groupNode);remove(fruitArray,
obj);Pool.remove(obj.fruitAmmo.id);Pool.remove(obj.transportUFO.id);screenFruitNum--;log.debug("screenFruitNum:"+screenFruitNum);if(screenFruitNum==0)GameEvent.trigger("stateEvent","fruitDisappear")}}})}}function giveUpFruitAmmo(obj){if(!gpause){unbindTimer(obj.fightFunc);obj.status="giveUp";var startPos=obj.fruitAmmo.node.translation;var endPos=getFruitByTranUFO(obj.transportUFO.node.translation);if(getVector(startPos,endPos).length()<=fruitERange){obj.stop=false;return}var _init=true;obj.fruitSpeed=
getSpeedVector(startPos,endPos,fruitBackSpeed);TimerEvent.bind("time",function(t,dt){if(_init){obj.giveUpFunc=arguments.callee;_init=false}var condition=obj.status=="giveUp";if(!gpause&&condition){var distance=moveFruit(obj,endPos,dt);if(distance<=fruitERange){unbindTimer(obj.giveUpFunc);obj.stop=false}}else if(!condition)unbindTimer(obj.giveUpFunc)})}}function escape(obj,endPos,dt){var v=obj.escapeSpeed;obj.transportUFO.node.translation=plus(obj.transportUFO.node.translation,v.multiply(dt));var distance=
getVector(obj.transportUFO.node.translation,endPos).length();return distance}exports.hurlUFO=function(sourcePlace,targetNode){hurlFruitAmmo(selectFruitName,sourcePlace,targetNode)};function hurlFruitAmmo(fruitName,sourcePlace,targetNode){if(!gpause){var fruitAmmoNode=getFruitNode(fruitName,1).node;fruitAmmoNode.node.translation=sourcePlace;group.children[0].addChild(fruitAmmoNode.node);var obj={"node":fruitAmmoNode,"func":null};ammoArray.push(obj);var _init=true;TimerEvent.bind("time",function(t,
dt){if(_init){ammoSpeed=ammoStartSpeed;obj.func=arguments.callee;_init=false}if(!gpause){var distance=moveAmmo(fruitAmmoNode,targetNode,dt);if(distance<=hitERange){unbindTimer(obj.func);hitUFO(obj);GameEvent.trigger("stateEvent","hitting")}}})}}function moveAmmo(resourceNode,targetNode,dt){ammoSpeed=ammoSpeed+ammoAccSpeed*dt;if(ammoSpeed>=ammoEndSpeed)ammoSpeed=ammoEndSpeed;var v=getSpeedVector(resourceNode.node.translation,targetNode.translation,ammoSpeed);resourceNode.node.translation=plus(resourceNode.node.translation,
v.multiply(dt));var distance=getVector(resourceNode.node.translation,targetNode.translation).length();return distance}function hitUFO(obj){group.children[0].removeChild(obj.node.node);Pool.remove(obj.node.id);for(var i=0;i<ammoArray;i++)if(ammoArray[i]==obj)ammoArray.splice(i,1)}function showUFO(){var nodeStr="Transform {translation -8 0 -55 children[Material{diffuseColor 1 0 0} Box{size 0.6 0.6 0.6}]}";targetNode=new SFNode(nodeStr);group.children[0].addChild(targetNode);Timer.bindFraction(8,function(f){if(f<=
0.5)targetNode.translation=new SFVec3f(32*(f-0.5)+8,0,-85);else targetNode.translation=new SFVec3f(32*(1-f)-8,0,-85)},function(){return true})}exports.destroy=function(){if(state){state=false;enabledEvents(false);exit()}};function exit(){var obj;if(fruitArray.length>0){for(var i=0;i<fruitArray.length;i++){obj=fruitArray[i];unbindTimer(obj.runFunc);unbindTimer(obj.fightFunc);unbindTimer(obj.giveUpFunc);unbindTimer(obj.escapeFunc);group.children[0].removeChild(obj.groupNode);Pool.remove(obj.fruitAmmo.id);
Pool.remove(obj.transportUFO.id)}fruitArray=[]}if(ammoArray.length>0){for(var i=0;i<ammoArray.length;i++){obj=ammoArray[i];unbindTimer(obj.func);group.children[0].removeChild(obj.node.node);Pool.remove(obj.node.id)}ammoArray=[]}gpause=false;activateFruit=null;previousFruit=null;if(debug)SystemEvent.unBind("keyUp",null);GROUPMID.removeChild(group)}});
