define(
	{
		"base":"resources/avatars/et002/",
		"bone":"bone.csf",
		"meshSet":[
			{
				"name":"normal",
				"mesh":["mesh.cmf"]
			}
		],
		"texture":"waixingren_02.jpg",
		"animation":{
			"fly":{"alias":"fly","type":1,"name":"ani1.caf"},
            "faint":{"alias":"faint","type":1,"name":"ani2.caf"},
            "dead":{"alias":"dead","type":1,"name":"ani3.caf"}
}
	}
);