define(function(require,exports,module){var root=this,state=false,basePath,lyxName,reSelect=false,log=require("core/Logger").getLog(),GameEvent=require("core/Event").getInstance("GameEvent"),UFO=require("./Ufo"),Timer=require("core/Timer"),pool=require("node/NodeCachePool"),ProtoLoader=require("node/ProtoLoader"),Config=require("./Config"),MyGroup;var UFOMap={},listTimer=[],camera=Config.camera.position;var aimNode;exports.init=function(){if(!state){MyGroup=new SFNode("DEF ufoTrans Transform{}");
GROUPMID.addChild(MyGroup);basePath=Config.ufo.basePath;startUFO();createUFO();createAim();driver();selectDriver();state=true}};function startUFO(){for(var i=0,len=Config.global.ufoNum;i<len;i++){var ufo=createModel();UFOMap[ufo.id]=ufo}}function createAim(){var nodeName=ProtoLoader.load(RS.protos.Aim);aimNode=(new SFNode("Switch { choice [ Transform { children ["+nodeName+"{} ] }] whichChoice -1 }")).children[0];MyGroup.addChild(aimNode)}function createUFO(){var sTime=Date.now();listTimer[0]=Timer.bindTime(function(t){if(t-
sTime>=Config.global.targetCycle){var ufo=createModel();UFOMap[ufo.id]=ufo;sTime=t}})}function createModel(){var ufo,obj,model,lyxName,type;switch(Math.round(Math.random()*4)){case 0:model=Config.ufo.ufo001;break;case 1:model=Config.ufo.ufo002;break;case 2:model=Config.ufo.ufo003;break;case 3:model=Config.ufo.ufo004;break;case 4:model=Config.ufo.ufo005;break}obj=pool.create(model.lyxName,null,basePath);ufo=UFO.getInstance(obj.node,obj.id,model.type,model.worth,model.startSpeed,model.hitSpeed,model.config);
MyGroup.addChild(obj.node);return ufo}var intoNum=0;function driver(){listTimer[1]=Timer.bindDTime(function(dt){for(var key in UFOMap){var ufo=UFOMap[key];var vec=ufo.target.subtract(ufo.start);if(ufo.state=="flying"||ufo.state=="hit"){ufo.node.translation.setValue(ufo.node.translation.add(vec.normalize().multiply(ufo.flySpeed+0.2).multiply(dt)));ufo.flySpeed=ufo.node.translation.subtract(ufo.target).length()/vec.length()*ufo.startSpeed;if(ufo.isSelect){aimNode.choice[0].translation.setValue(ufo.node.translation);
aimNode.choice[0].children[0].translation.setValue(ufo.config.translation)}if(ufo.target.subtract(ufo.node.translation).length()<0.2){remove(ufo);intoNum++;if(intoNum>=Config.global.intoNum)GameEvent.trigger("stateEvent","failed")}}else if(ufo.state=="dead"){ufo.node.translation.setValue(ufo.node.translation.add(vec.normalize().multiply(ufo.hitSpeed).multiply(dt)));if(ufo&&ufo.node&&ufo.node.scale[0]>0.01)ufo.node.scale.setValue(ufo.node.scale.multiply(0.95));if(ufo.node.translation.subtract(ufo.target).length()<=
5)remove(ufo)}}})}function remove(ufo){if(ufo.isSelect){select.isSelect=false;aimNode.whichChoice=-1}MyGroup.removeChild(ufo.node);pool.remove(ufo.id);delete UFOMap[ufo.id]}function addAmi(select){aimNode.choice[0].translation.setValue(select.node.translation);aimNode.choice[0].children[0].translation.setValue(select.config.translation);aimNode.choice[0].children[0].scale.setValue(select.config.scale);aimNode.choice[0].children[0].life1State=0;if(select.config.blood==2){aimNode.choice[0].children[0].life=
-3;if(select.curBlood==1)aimNode.choice[0].children[0].life2State=1;else if(select.curBlood==2)aimNode.choice[0].children[0].life2State=0}else if(select.config.blood==1)aimNode.choice[0].children[0].life=0;aimNode.whichChoice=-3;select.isSelect=true}var listSelect;function checkLook(){var i=-1;listSelect=[];for(var key in UFOMap){var ufo=UFOMap[key];var ufoZ=ufo.node.translation[2];if(ufo.state!="dead"&&ufoZ<Config.select.selectLimit[0]&&ufoZ>Config.select.selectLimit[1])listSelect[++i]=ufo}var len=
listSelect.length;if(len!=0){listSelect.sort(function(a,b){return a.target.subtract(a.node.translation).length()-b.target.subtract(b.node.translation).length()});var n=Math.floor(Math.random()*Math.min(len,Config.select.selectNum));select=listSelect[n];addAmi(select)}}var select;function selectUFO(){if(select){select.isSelect=false;aimNode.whichChoice=-1}checkLook()}exports.startSelect=function(){reSelect=false;selectUFO();reSelect=true;startTime=Date.now()};var startTime;function selectDriver(){startTime=
Date.now();listTimer[2]=Timer.bindTime(function(t){if(reSelect){var time=t-startTime;if(time>=Config.global.selectCycle){selectUFO();startTime=t}}})}exports.hit=function(){if(!select)return;log.info("-----------------");select.curBlood--;if(select.curBlood==1){aimNode.choice[0].children[0].life2State=1;select.state="hit"}else if(select.curBlood==0){aimNode.choice[0].children[0].life1State=1;select.state="dead";select.start=new SFVec3f(select.node.translation);select.target=setNewTarget()}listTimer[3]=
setTimeout(function(){aimNode.whichChoice=-1;select.isSelect=false;clearTimeout(listTimer[3])},0.1);return select.curBlood==0?{"score":select.worth,"type":select.type}:{"score":0,"type":select.type}};function setNewTarget(){var x,nearWidth=UFO.getLookWidth(Config.camera.near);if(select.node.translation.x<camera[0])x=-2*nearWidth;else x=2*nearWidth;return new SFVec3f(x,select.node.translation.y,select.node.translation.z)}exports.getTarget=function(){if(select&&select.isSelect){reSelect=false;return select.node}return null};
exports.destroy=function(){if(state){state=false;clearTimer();UFOMap=[];listTimer=[]}};function clearTimer(){for(var i=0,len=listTimer.length;i<len;i++)Timer.clear(listTimer[i])}});
